name: gadget_board
description: App to connect to Aemics' Gadget Board.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.5.0
  tflite_flutter: ^0.9.0
  path: ^1.8.0
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  lint: ^1.8.2
  splashscreen: ^1.3.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  usb_serial: ^0.4.0
  crclib: ^3.0.0

flutter:
  assets:
    - assets/nn_quad.tflite
    - assets/min_max_quad.txt
    - assets/nn_square.tflite
    - assets/min_max_square.txt
    - assets/nn_led.tflite
    - assets/min_max_led.txt
    - icons/aemics-logo.png
    - icons/aemics-icon.png
  uses-material-design: true

flutter_icons:
  image_path: "icons/gadget_board.png" 
  android: true
  ios: true